services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql1biblio
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Root12345678"
    ports:
      - "1433:1433"
